version: '2'

networks:
    default:
        external:
            name: dev

services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:cached #for Mac
            - ./nginx-proxy/my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf:cached #for Mac
            
    memcached:
        image: memcached:latest
        container_name: memcached

    mysql:
        image: mysql:5.6
        container_name: mysql
        ports:
            - "3306:3306"
        volumes:
            - ./.data/mysql:/var/lib/mysql:cached #for Mac
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root

    portainer:
        image: portainer/portainer
        container_name: management_panel
        ports:
            - "9900:9000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:cached #for Mac
            - ./.data/portainer:/data:cached #for Mac

    php:
        image: toxaco/signaturedockerenv
        container_name: signature
        environment:
            VIRTUAL_HOST:   "dev.loan.co.uk"
            PHP_IDE_CONFIG: "serverName=loan.php"
            SSH_AUTH_SOCK:  "/ssh-agent"
            CERT_NAME:      "dev"
        external_links:
            - memcached
            - mysql
        volumes:
           - ./../application/:/var/www/html:cached #for Mac
           - /etc/localtime:/etc/localtime:cached #for Mac #make sure datetime sync with host.
           - ./config/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:cached #for Mac
           - ./config/nginx.conf:/etc/nginx/nginx.conf:cached #for Mac
        command: 
           - "/usr/bin/supervisord"

