version: '2'

networks:
    default:
        external:
            name: dev

services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:cached #for Mac
            - ./nginx-proxy/my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf:cached #for Mac
    # redis:
    #     image: redis:latest
    #     container_name: redis

    memcached:
        image: memcached:latest
        container_name: memcached

    mysql:
        image: mysql:5.7
        container_name: mysql
        ports:
            - "3306:3306"
        volumes:
            - ./.data/mysql:/var/lib/mysql:cached #for Mac
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root

    portainer:
        image: portainer/portainer
        container_name: management_panel
        ports:
            - "9900:9000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:cached #for Mac
            - ./portainer:/data:cached #for Mac

