version: '2'

networks:
    default:
        external:
            name: dev

services:

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: signature
        environment:
            VIRTUAL_HOST:   "dev.loan.co.uk"
            PHP_IDE_CONFIG: "serverName=loan.php"
            SSH_AUTH_SOCK:  "/ssh-agent"
            CERT_NAME:      "dev"
        external_links:
            - memcached
            - mysql
        volumes:
           - ./../application/:/var/www/html:cached #for Mac
           - /etc/localtime:/etc/localtime:cached #for Mac #make sure datetime sync with host.
           - ./config/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:cached #for Mac

